### ISSUE TITLE
Radio Button Instantiation

### ISSUE THREAD

**Issue by Brett-Best** [rhx/SwiftGtk#12]
Hi Rene,

I’m creating a group of radio buttons and I’ve got two questions if you wouldn’t mind pointing me in the right direction that would be great.

1. How can I (if possible) create the first radio button without using the C function directly?
I tried doing something like this:
```swift
RadioButton(label: nil, label: “Red LED")
```
However, it didn’t compile because the first parameter isn’t optional.

2. Does a cleaner way of passing in the group exist?
```swift
SList(redLEDRadioButton.group)
```

###### Radio Button Code
```swift
  let redGtkRadioButton = gtk_radio_button_new_with_label(nil, "Red LED")!
  let redLEDRadioButton = RadioButton(cPointer: redGtkRadioButton)
  box.packStart(child: redLEDRadioButton, expand: true, fill: true, padding: 8)
  
  let greenLEDRadioButton = RadioButton(label: SList(redLEDRadioButton.group), label: "Green LED")
  box.packStart(child: greenLEDRadioButton, expand: true, fill: true, padding: 8)
  
  let blueLEDRadioButton = RadioButton(label: SList(greenLEDRadioButton.group), label: "Blue LED")
  box.packStart(child: blueLEDRadioButton, expand: true, fill: true, padding: 8
```

Thanks!

**Comment by rhx** [comment]
I have now added convenience initialisers that only take a label, e.g. to create the first button of a group.  Also, anything that has to do with singly-linked lists now returns an `SListRef` instead of an `UnsafeMutablePointer<GSList>`.  So your code can now be written as:
```Swift
let redLEDRadioButton = RadioButton(label: "Red LED")
box.packStart(child: redLEDRadioButton, expand: true, fill: true, padding: 8)

let greenLEDRadioButton = RadioButton(group: redLEDRadioButton.group, label: "Green LED")
box.packStart(child: greenLEDRadioButton, expand: true, fill: true, padding: 8)

let blueLEDRadioButton = RadioButton(group: greenLEDRadioButton.group, label: "Blue LED")
box.packStart(child: blueLEDRadioButton, expand: true, fill: true, padding: 8)
```

Also, there is now a convenience initialiser, if you want to create a group of buttons from a list of labels:
```Swift
let rgbButtons = RadioButton.groupLabeled("Red LED", "Green LED", "Blue LED")
for button in rgbButtons {
    box.packStart(child: button, expand: true, fill: true, padding: 8)
}
```

You can find a simple example at: https://github.com/rhx/SwiftHelloGtkRadioButtons

**Comment by Brett-Best** [comment]
Thanks, that works perfectly!
