### ISSUE TITLE
Update Mac dependencies in README

### ISSUE THREAD

**Issue by lschmierer** [rhx/SwiftGtk#15]
`brew install gtk+3` does not satisfy all dependencies on a clean Mac installation.

`gobject-introspection` and `pkg-config` needs to be installed as well.

```
brew install gtk+3 gobject-introspection pkg-config
```

The same applies to the example projects like https://github.com/rhx/SwiftHelloGtk

**Comment by rhx** [comment]
Thanks.  I have updated the corresponding README's now.
