### ISSUE TITLE
More idiomatic way to work with events

### ISSUE THREAD

**Issue by lschmierer** [rhx/SwiftGtk#24]
How can I access event struct fields without accessing `_ptr`?
```Swift
connectKey(signal: "key_press_event") { _, event in
    let event = event._ptr.pointee
    debugPrint(event.keyval)
}
```

**Comment by rhx** [comment]
Swift doesn't support C-style unions such as `GdkEvent`, so there is no corresponding Swift wrapper with more idiomatic properties at the moment.  I'll have a think if there is a way to teach `gir2swift` some magic to work around this ...

**Comment by rhx** [comment]
With SwiftGtk 3.24.17 and gir2swift 10, you can now access `GdkEvent` fields directly from Swift.  Also, you probably want to use `onKey` or `onKeyPress` instead of `connectKey`, e.g.:
```Swift
        widget.onKeyPress { widget, event in
            let key = event.keyval
            let hw = event.hardwareKeycode
            // ...
        }

        canvas.onKey(event: .keyPressEvent) { widget, event in
            let key = event.keyval
            let hw = event.hardwareKeycode
            // ...
        }
```
