### ISSUE TITLE
Examples not building with latest SwiftGtk

### ISSUE THREAD

**Issue by lschmierer** [rhx/SwiftGtk#26]
Building the example projects (like `SwiftHelloGtk`) fails with a bunch of errors like
```
/.../SwiftHelloGtk/.build/checkouts/SwiftGObject/Sources/GLibObject/GObject-2.0-bitfields.swift:110:45: error: use of unresolved identifier 'G_PARAM_READABLE'
    public static let readable = ParamFlags(G_PARAM_READABLE) /* 1 */
```
As far as I can tell this was introduced by the changes for https://github.com/rhx/SwiftGtk/issues/25 commit 9ec828068dc8e875baa1df098e99541679e991e4.

**Comment by lschmierer** [comment]
Unfortunately, it is not even possible to revert to an older version of `SwiftGtk` and `gir2swift` due to the `.branch("master")` dependencies.
Using an older version of `SwiftGtk` still pulls the `master` of `SwiftAtk`, `SwiftGObject`, etc.

**Comment by rhx** [comment]
There seems to be a bug in the Swift compiler where the C symbols sometimes aren't available (despite CGtk, CGObject, etc. being imported).  The strange thing is that it worked fine for me when I tested it with SwiftHelloGtk and it does work fine when compiling/testing the individual modules (e.g. SwiftGObject).

When I test it now, I get no error for CGObject, but a similar one for GTK_RC_FG in CGtk.

When I try to find out what's going on, I get the error message "SourceKit: Couldn't Generate Swift Representation - Could not load CGtk".

I'll investigate and see if there is a workaround.

**Comment by rhx** [comment]
Okay, I have committed a workaround that uses the numerical values from the gir file rather than the constants in the C header file.  So this should be fixed when using the current version of gir2swift (9.0.1).  Make sure you do a `./clean.sh` before rebuilding.
