### ISSUE TITLE
Not building with latest GTK on Mac (Home-brew GTK 3.24.21)

### ISSUE THREAD

**Issue by lschmierer** [rhx/SwiftGtk#28]
With GTK 3.24.21, pkg-config adds additional commas after the `-framework` flag like `-framework,Cocoa`.

Using something like `| tr ',' ' '` or adapting the the `sed` parameters for `LINKFLAGS` in `config.sh` fixes this.

**Comment by rhx** [comment]
Fixed now, thank a lot!

**Comment by lschmierer** [comment]
This needs to be changed for the example projects like https://github.com/rhx/SwiftHelloGtk as well, I guess.

**Comment by rhx** [comment]
Yes.  They should all be updated by now.
