### ISSUE TITLE
Gtk4 support

### ISSUE THREAD

**Issue by migueldeicaza** [rhx/SwiftGtk#38]
Hello,

Gtk+ 4.0 will be released this week, and it features a much nicer rendering system than Gtk+ 3.0, and wanted to get a place going to discuss what it would take to get Gtk+ 4.0 support in place.

**Comment by rhx** [comment]
Shouldn't be too difficult (I hope), at least for those parts that are automatically translated using gir2swift.  I'll have a look an see what it takes to get gtk+4 to install on macOS ...

**Comment by rhx** [comment]
Gtk+ 4.0 is now supported through the gtk4 branch.

**Comment by migueldeicaza** [comment]
Oh thank you!   This is wonderful!

Cheers!
