### ISSUE TITLE
Building SwiftGtk results in error with SwiftGObject

### ISSUE THREAD

**Issue by jenra-uwu** [rhx/SwiftGtk#42]
I get the following error when building SwiftGObject with SwiftGtk on arch linux:
```
error: SwiftGObject is required using two different revision-based requirements (master and main), which is not supported
```

**Comment by WilliamBehrens** [comment]
I'd like to second this, I've gotten the same issue on linux, even when trying to compile one of the pre-existing examples using the build scripts I still get the same issue.

**Comment by rhx** [comment]
Fixed, thanks!

All dependencies have now switched to the main branch.  I'll keep around master for a little bit longer, but best to ensure that your packages now depend on "main" rather than "master" to avoid similar issues.
