### ISSUE TITLE
prohibited flag(s): -pthread

### ISSUE THREAD

**Issue by chrisvalford** [rhx/SwiftGtk#50]
Attempting to use on both Rasperry PI Buster (64 bit) and Ubuntu 20.04.2 LTS has the same error
CGLib & CGdkPixbuf - warning: prohibited flag(s): -pthread
Then multiple errors like 
public extension Mutex {
error: cannot find 'Mutex' in scope

**Comment by mikolasstuchlik** [comment]
Hello,

the warning about -pthread is normal.

I would like to ask you for more information regarding the error. What version of Swift are you using. Have you executed `build.sh` or `run-gir2swift.sh` before build?

You need to generate Swift wrapper around the Gtk first. (The process takes time, several minutes on my Pi 4.)

**Comment by rhx** [comment]
I am closing this for now.  This really is a (largely cosmetic) issue with how Swift interacts with pkg-config.  The other error described here seems unrelated.
