### ISSUE TITLE
Swift 5.5 issues

### ISSUE THREAD

**Issue by mikolasstuchlik** [rhx/SwiftGtk#51]
Swift 5.5 has already been tested with the SwiftGtk.

Resolved issues and bugs:
- The Swift 5.5 contains improved SPM and resolves https://github.com/rhx/SwiftGtk/issues/43

New issues and bugs:
- [x] The Swift 5.5 version of SPM changes the behavior of `swift package dump-package`. This leads to false negative result of `is_processable` function. The issue is fixed by removing lines 12 and 13 from `gir2swift-generation-driver.sh` and modifying the if condition.
- [x] The Swift 5.5 requires additional import. The type `passwd` now cannot be used unless `pwd.h` is included in the SwiftGLib package.

**Comment by rhx** [comment]
Thanks!  I have updated [gir2swift](https://github.com/rhx/gir2swift) and [SwiftGLib](https://github.com/rhx/SwiftGLib) accordingly now.
