### ISSUE TITLE
GTK MainLoop and Swift/Foundation MainLoop Integration

### ISSUE THREAD

**Issue by austintatiousness** [rhx/SwiftGtk#56]
How does one go about integrating the Swift/Foundation main loop with GTK MainLoop. Specifically, I need concurrency (Tasks, _et cetera_)  to work properly.

**Comment by rhx** [comment]
What you probably want to look at is using the standard Swift/Foundation RunLoop together with [mainIterationDo(blocking: false)](https://rhx.github.io/SwiftGtk3Doc/Functions.html#/s:3Gtk15mainIterationDo8blockingS2b_tF).  This way you can make both runloops co-exist.
