### ISSUE TITLE
Unneeded include prevents build

### ISSUE THREAD

**Issue by jamgard** [rhx/SwiftGtk#58]
In the SwiftCairo/Sources/CCairo/cairo_bridging.h file there is a reference to cairo-tee.h and it prevents building on Manjaro Linux. The current Cairo version is 1.17 and doesn't include cairo-tee.h and after removing the reference in the SwiftGtk SwiftCairo source file, the build completes and the tests pass.

**Comment by rhx** [comment]
I have now removed `cairo-tee.h` for cairo-1.17 and higher.  Could you double-check that this works for you (don't forget to `swift package purge-cache ; rm -f Package.resolved ; swift package upgrade` to ensure the new SwiftCairo is pulled in when re-compiling).

**Comment by jamgard** [comment]
It builds now. Thank you for the change.
