### ISSUE TITLE
/home/gaofeng/Desktop/swift_projects/gtk-demo/.build/checkouts/SwiftGLib/Sources/GLib/TypedSequence.swift:222:25: error: value of type 'gpointer' (aka 'UnsafeMutableRawPointer') has no member 'withMemoryRebound'             return data.withMemoryRebound(to: Element.self, capacity: 1) {

### ISSUE THREAD

**Issue by Naonao9527** [rhx/SwiftGtk#59]

**Comment by Naonao9527** [comment]
swift5.6.2 ubuntu20.04(wsl)

**Comment by rhx** [comment]
Thanks for spotting, this was using a Swift-5.7 API.  I have committed a fix that makes it compile again with Swift-5.6.x.  Could you run `swift package purge-cache ; rm -rf .build ; swift package update` and then try again, please?

**Comment by Naonao9527** [comment]
Ok, it's up and running
好了，它可以运行了
