### ISSUE TITLE
provide API documentation

### ISSUE THREAD

**Issue by medovina** [rhx/SwiftGtk#6]
Again, SwiftGtk is great!

I can often guess the name and parameters of a SwiftGtk wrapper function based on the corresponding name and parameters in the GTK documentation, but sometimes it's not immediately obvious and I have to look through the wrapper source files to find the function.  So it would be nice if SwiftGtk provided reference documentation for its API, ideally in a format like that at http://swiftdoc.org/ .

**Comment by lf-araujo** [comment]
@medovina have you successfuly created any app with swiftgtk that you can showcase?

**Comment by medovina** [comment]
@lf-araujo No - I've just begun playing with SwiftGTK in the last week.  The toy experiments I've written so far have worked well, however.

**Comment by carlhung** [comment]
It would be great if more tutorials can be added.

**Comment by rhx** [comment]
API documentation is now available on https://rhx.github.io/SwiftGtk

Also, the generated sources now contain SwiftDoc style documentation, so if you use ./xcodegen.sh to generate an Xcode project for your package, the documentation should show up in the help viewer.
