### ISSUE TITLE
swift build not working in ubuntu 22.04 ,ncompatible integer to pointer conversion returning 'GType' 

### ISSUE THREAD

**Issue by A373k** [rhx/SwiftGtk#60]
: error: incompatible integer to pointer conversion returning 'GType' (aka 'unsigned long') from a function with result type 'GTypeClass *' (aka 'struct _GTypeClass *') [-Wint-conversion]
    return G_TYPE_FROM_INSTANCE(gobject);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/gobject/gtype.h:619:65: note: expanded from macro 'G_TYPE_FROM_INSTANCE'
#define G_TYPE_FROM_INSTANCE(instance)                          (G_TYPE_FROM_CLASS (((GTypeInstance*) (instance))->g_class))
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[2/7] Converting Gtk Gtk-3.0.gir

**Comment by rhx** [comment]
Thanks for reporting, this should be fixed now.  This was actually an issue in SwiftGObject, not SwiftGtk, so if you are on the `main` or `gtk4` branch, make sure you update your dependencies before rebuilding, i.e.:
```sh
rm -rf .build
swift package purge-cache
swift package update
```
